export const PATH = "https://norma.nomoreparties.space/api";
export const INGREDIENTS_URL = `${PATH}/ingredients`;
export const CREATED_ORDER_URL = `${PATH}/orders`;
export const PASSWORD_RESET_URL = `${PATH}/password-reset`;
export const CREATE_USER_URL = `${PATH}/auth/register`;
export const AUTH_LOGIN_USER_URL = ` ${PATH}/auth/login`;
export const REG_USER_URL = `${PATH}/auth/register`;
export const LOGOUT_URL = `${PATH}/auth/logout `; /*POST- эндпоинт для выхода из системы.*/
export const UPDATE_TOKEN_URL = `${PATH}/auth/token /`;
export const PASSWORD_RESET_RESET_URL = `${PATH}/password-reset/reset`;
export const AUTH_GET_USER_URL = `${PATH}/auth/user `; /* эндпоинт получения данных о пользователе. GET*/
export const AUTH_PATCH_USER_URL = `${PATH}/auth/user `; /*PATCH эндпоинт обновления данных о пользователе*/
